In [2]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score

In [3]:
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
import pickle as pkl

In [4]:
warnings.filterwarnings('ignore')

In [5]:
# loading dataset
try:
    df = pd.read_csv('data/customers.csv')
except FileNotFoundError:
    print("Data set file nhi hai data folder me")
    exit()

In [6]:
df = pd.read_csv('data/customers.csv')

In [7]:
df.rename(columns={'Annual Income (k$)': 'Annual Income', 'Spending Score (1-100)': 'Spending Score'}, inplace=True)
df.sample(5)

     CustomerID  Gender  Age  Annual Income  Spending Score
107         108    Male   54             63              46
14           15    Male   37             20              13
31           32  Female   21             30              73
172         173    Male   36             87              10
160         161  Female   56             79              35

In [9]:
# preprocesing piplines

categorical_feature = ['Gender']
numerical_features = ['Age', 'Annual Income', 'Spending Score']

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_feature)
    ]
)

new_df = df.drop('CustomerID', axis=1)

In [10]:
new_df.head()

   Gender  Age  Annual Income  Spending Score
0    Male   19             15              39
1    Male   21             15              81
2  Female   20             16               6
3  Female   23             16              77
4  Female   31             17              40

In [11]:
# Fit preprocessor
new_df_processed = preprocessor.fit_transform(new_df)
# transforming data also

In [14]:
# same as a pickel file
with open('models/preprocessors.pkl', 'wb') as f:
    pkl.dump(preprocessor, f)